//// <auto-generated />
//using System;
//using EmployeeManagement.Database.Context;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace EmployeeManagement.Database.Migrations
//{
//    [DbContext(typeof(ApplicationDbContext))]
//    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "6.0.6")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

//            modelBuilder.Entity("EmployeeManagement.Database.Context.Models.Employee", b =>
//                {
//                    b.Property<Guid>("EmployeeID")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<DateTime>("CreateDate")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("CreatorAdd")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("CreatorEdit")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<DateTime?>("DateOfBirth")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Email")
//                        .HasMaxLength(250)
//                        .HasColumnType("nvarchar(250)");

//                    b.Property<string>("FullName")
//                        .HasMaxLength(150)
//                        .HasColumnType("nvarchar(150)");

//                    b.Property<bool>("IsDelete")
//                        .HasColumnType("bit");

//                    b.Property<DateTime>("ModifiedDate")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("PassWord")
//                        .HasMaxLength(500)
//                        .HasColumnType("nvarchar(500)");

//                    b.Property<string>("Phone")
//                        .HasMaxLength(20)
//                        .HasColumnType("nvarchar(20)");

//                    b.Property<int>("Sex")
//                        .HasColumnType("tinyint");

//                    b.HasKey("EmployeeID");

//                    b.ToTable("Employee");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
